### ISSUE TITLE
Schwimmbäder ohne korrekte Adressen

### ISSUE THREAD

**Issue by botic** [botic/ogd-wien-issues#1]
### Datensatz
[Schwimmbäder Standorte Wien](https://www.data.gv.at/katalog/dataset/898afe8c-0297-45d6-b4b5-0cb9e632094b)

### Fehlerbeschreibung
Adressen sind keine gültigen Adressen, sondern nur grobe Angaben zum Eingangsbereich. Beispiele:

- Gudrunstraße, Ecke Absberggasse
- Herderpark, Herderplatz
- …

### Verbesserung / Bugfix

Jedes Schwimmbad mit einer korrekten (Post-)Adresse im Format `Straßenname ONR` versehen und Angaben zum Eingangsbereich in einem Beschreibungs- oder Infofeld anbringen.

**Comment by botic** [comment]
Reported: https://www.partizipation.wien.at/idea/333648/8599

**Comment by hactar** [comment]
Schwimmbäder sind auch teilweise ungünstig benannt. "Brigittenau" statt "Brigittenauer Bad". THERME WIEN statt Therme Wien. Wurde auch gemeldet.

**Comment by botic** [comment]
> Ergebnis:  Bei den Bädern, die über eine Postadresse verfügen, ist diese auch angegeben. Die meisten Familienbäder verfügen jedoch über keine Postadresse, weil sie inmitten eines Parks liegen. Daher wird versucht, eine Zugangsbeschreibung anzugeben. (detaillierte Antwort s.u.)
